### PR TITLE
Add Replicate demo and API 

### PR DESCRIPTION
**Pull request by chenxwh**
Hi @jiaxiangc,

Very cool project on `res-adapter`!

This pull request makes it possible to run `res-adapter` on Replicate (https://replicate.com/cjwbw/res-adapter) and via API (https://replicate.com/cjwbw/res-adapter/api). Currently, there is an option to output both with and without the adapter for comparison.  Also we'd like to transfer the demo page to `bytedance` so you can make modifications easily, but happy to help maintain/integrate the upcoming changes,  :)

### CODE REVIEW

**Comment by jiaxiangc** [comment]
Thanks for your contribution. We will merge your pr, and make some change to your codes.

**Comment by jiaxiangc** [comment]
@chenxwh Can we contribute this demo together? I actually do not know how to building demo in replicate, and there is no person to accept me to join bytedance in replicate.

**Comment by chenxwh** [comment]
> @chenxwh Can we contribute this demo together? I actually do not know how to building demo in replicate, and there is no person to accept me to join bytedance in replicate.

Definitely I'd love to! I'll drop you an email to see how we can best work on this together:)

**Comment by chenxwh** [comment]
@jiaxiangc I just sent you an email :)

**Pull request merged**
